// lib/paths.ts

export const PATHS = {
  core: {
    engines: {
      prep: "core/engines/engine-prep.js",
      proto: "core/engines/engine-proto.js",
      shotgun: "core/engines/engine-shotgun.js",
      xpGrind: "core/engines/engine-xp-grind.js",
      jitBatcher: "core/engines/sys-jit-batcher.js",
    },
    boot: "core/boot.js",
    financeCore: "core/finance-core.js",
    purchaseAction: "core/purchase-action.js",
    apocalypse: "core/sys-apocalypse.js",
    dispatcher: "core/sys-dispatcher.js",
    jitDashboard: "core/sys-jit-batcher-dashboard.js",
    kernel: "core/sys-kernel.js",
    logger: "core/sys-logger.js",
    orchestrator: "core/sys-orchestrator.js",
    shotgutDashboard: "core/sys-shotgun-dashboard.js",
    suites: "core/sys-suites.js",
  },
  daemons: {
    backdoor: "daemons/backdoor.js",
    crawler: "daemons/dnet-crawler.js",
    fillShare: "daemons/fill-share.js",
    financeManager: "daemons/finance-manager.js",
    perfMonitor: "daemons/perf-monitor.js",
    suite: "daemons/suite-manager.js",
  },
  lib: {
    evaluators: {
      gang: "lib/evaluators/gang.js",
      hacknet: "lib/evaluators/hacknet.js",
      home: "lib/evaluators/home.js",
      player: "lib/evaluators/player.js",
      programs: "lib/evaluators/programs.js",
      pserv: "lib/evaluators/pserv.js",
      sleeve: "lib/evaluators/sleeve.js",
      stock: "lib/evaluators/stock.js",
    },
    types: {
      batcher: "lib/types/batcher.js",
      common: "lib/types/common.js",
      factions: "lib/types/factions.js",
      finance: "lib/types/finance.js",
      gang: "lib/types/gang.js",
      logger: "lib/types/logger.js",
      network: "lib/types/network.js",
      sleeves: "lib/types/sleeves.js",
      strategy: "lib/types/strategy.js",
    },
    constants: "lib/constants.js",
    faction: "lib/faction-helpers.js",
    format: "lib/format.js",
    gang: "lib/gang-utils.js",
    logger: "lib/logger-client.js",
    metrics: "lib/metrics.js",
    network: "lib/network.js",
    paths: "lib/paths.js",
    player: "lib/player.js",
    sleeve: "lib/sleeve-utils.js",
    state: "lib/state.js",
    utils: "lib/utils.js",
    executor: "lib/worker-executor.js",
  },
  managers: {
    dnet: "managers/dnet-master.js",
    finance: "managers/finance-manager.js",
    gang: "managers/gang-manager.js",
    infra: "managers/infra-manager.js",
    sleeve: "managers/sleeve-manager.js",
  },
  payloads: {
    grow: "payloads/grow.js",
    hack: "payloads/hack.js",
    share: "payloads/share.js",
    weaken: "payloads/weaken.js",
    work: "payloads/work.js",
  },
  solvers: {
    AccountsManager: "solvers/solveAccountsManager.js",
    Anagram: "solvers/solveAnagram.js",
    CloudBlare: "solvers/solveCloudBlare.js",
    DeepGreen: "solvers/solveDeepGreen.js",
    DeskMemo: "solvers/solveDeskMemo.js",
    FactoriOs: "solvers/solveFactoriOs.js",
    FreshInstall: "solvers/solveFreshInstall.js",
    Laika4: "solvers/solveLaika4.js",
    Manager: "solvers/solveManager.js",
    NIL: "solvers/solveNIL.js",
    OctantVoxel: "solvers/solveOctantVoxel.js",
    OpenWebAccessPoint: "solvers/solveOpenWebAccessPoint.js",
    PHP54: "solvers/solvePHP54.js",
    Pr0verFl0: "solvers/solvePr0verFl0.js",
    Roman: "solvers/solveRoman.js",
    ZeroLogon: "solvers/solveZeroLogon.js",
  },
  tasks: {
    analyzeAug: "tasks/analyze-augmentations.js",
    corp: "tasks/corp.js",
    crime: "tasks/crime.js",
    loot: "tasks/dnet-loot.js",
    phish: "tasks/dnet-phish.js",
    solver: "tasks/dnet-solver.js",
    faction: "tasks/faction-grind.js",
    train: "tasks/train.js",
    uni: "tasks/uni.js",
  },
  ui: {
    batcher: "ui/batcher-ui.js",
    gang: "ui/gang-ui.js",
    infra: "ui/infra-ui.js",
    shotgun: "ui/shotgun-ui.js",
    sleeve: "ui/sleeve-ui.js",
    helper: "ui/ui-helper.js",
  },
  utils: {
    batchCalculator: "utils/batch-calculator.js",
    deployment: "utils/deployment.js",
    offline: "utils/go-offline.js",
    internalPlanner: "utils/internal-planner.js",
    progress: "utils/progress.js",
    provision: "utils/provision.js",
    starter: "utils/starter.js",
  },
} as const;
