export const PATHS = {
  core: {
    boot: "core/boot.js",
    apocalypse: "core/sys-apocalypse.js",
    dispatcher: "core/sys-dispatcher.js",
    kernel: "core/sys-kernel.js",
    logger: "core/sys-logger.js",
    orchestrator: "core/sys-orchestrator.js",
    suites: "core/sys-suites.js",
    engines: {
      prep: "core/engines/engine-prep.js",
      proto: "core/engines/engine-proto.js",
      shotgun: "core/engines/engine-shotgun.js",
      xpGrind: "core/engines/engine-xp-grind.js",
      jitBatcher: "core/engines/sys-jit-batcher.js",
    },
  },
  daemons: {
    backdoor: "daemons/backdoor.js",
    crawler: "daemons/dnet-crawler.js",
    earlyFleet: "daemons/early-fleet.js",
    fillShare: "daemons/fill-share.js",
    hacknetEarly: "daemons/hacknet-early.js",
    hacknet: "daemons/hacknet.js",
    perfMonitor: "daemons/perf-monitor.js",
    suite: "daemons/suite-manager.js",
  },
  lib: {
    constants: "lib/constants.js",
    logger: "lib/logger-client.js",
    metrics: "lib/metrics.js",
    network: "lib/network.js",
    paths: "lib/paths.js",
    player: "lib/player.js",
    pserv: "lib/pserv-manager.js",
    sleeve: "lib/sleeve-utils.js",
    state: "lib/state.js",
    types: "lib/types.js",
    executor: "lib/worker-executor.js",
  },
  managers: {
    dnet: "managers/dnet-master.js",
    finance: "managers/finance-manager.js",
    infra: "managers/infra-manager.js",
    sleeve: "managers/sleeve-manager.js",
  },
  payloads: {
    grow: "payloads/grow.js",
    hack: "payloads/hack.js",
    share: "payloads/share.js",
    weaken: "payloads/weaken.js",
    work: "payloads/work.js",
  },
  solvers: {
    AccountsManager: "solvers/solveAccountsManager.js",
    Anagram: "solvers/solveAnagram.js",
    CloudBlare: "solvers/solveCloudBlare.js",
    DeepGreen: "solvers/solveDeepGreen.js",
    DeskMemo: "solvers/solveDeskMemo.js",
    FactoriOs: "solvers/solveFactoriOs.js",
    FreshInstall: "solvers/solveFreshInstall.js",
    Laika4: "solvers/solveLaika4.js",
    Manager: "solvers/solveManager.js",
    NIL: "solvers/solveNIL.js",
    OctantVoxel: "solvers/solveOctantVoxel.js",
    OpenWebAccessPoint: "solvers/solveOpenWebAccessPoint.js",
    PHP54: "solvers/solvePHP54.js",
    Pr0verFl0: "solvers/solvePr0verFl0.js",
    Roman: "solvers/solveRoman.js",
    ZeroLogon: "solvers/solveZeroLogon.js",
  },
  tasks: {
    analyzeAug: "tasks/analyze-augmentations.js",
    corp: "tasks/corp.js",
    crime: "tasks/crime.js",
    loot: "tasks/dnet-loot.js",
    phish: "tasks/dnet-phish.js",
    solver: "tasks/dnet-solver.js",
    faction: "tasks/faction-grind.js",
    augShopping: "tasks/faction-shopping.js",
    train: "tasks/train.js",
  },
  ui: {
    batcher: "ui/batcher-ui.js",
    infra: "ui/infra-ui.js",
    sleeve: "ui/sleeve-ui.js",
    helper: "ui/ui-helper.js",
  },
  utils: {
    batchCalculator: "utils/batch-calculator.js",
    deployment: "utils/deployment.js",
    offline: "utils/go-offline.js",
    infraExecutor: "utils/infra-sing-executor.js",
    internalPlanner: "utils/internal-planner.js",
    probeCorb: "utils/probe-corb.js",
    probeGang: "utils/probe-gang.js",
    probeSing: "utils/probe-sing.js",
    progression: "utils/progression.js",
    provision: "utils/provision.js",
    starter: "utils/starter.js",
  },
} as const;
