// lib/paths.ts

export const PATHS = {
  core: {
    actions: {
      cloud: "core/actions/act-cloud.ts",
      gang: "core/actions/act-gang.ts",
      hacknet: "core/actions/act-hacknet.ts",
      singularity: "core/actions/act-singularity.ts",
      sleeve: "core/actions/act-sleeve.ts",
      stock: "core/actions/act-stock.ts",
    },
    engines: {
      prep: "core/engines/engine-prep.js",
      proto: "core/engines/engine-proto.js",
      shotgun: "core/engines/engine-shotgun.js",
      xpGrind: "core/engines/engine-xp-grind.js",
      jitBatcher: "core/engines/sys-jit-batcher.js",
    },
    boot: "core/boot.js",
    financeCore: "core/finance-core.js",
    apocalypse: "core/sys-apocalypse.js",
    dispatcher: "core/sys-dispatcher.js",
    engineDashboard: "core/sys-engine-dashboard.js",
    jitDashboard: "core/sys-jit-batcher-dashboard.js",
    kernel: "core/sys-kernel.js",
    logger: "core/sys-logger.js",
    sysOrchestrator: "core/sys-orchestrator.js",
  },
  daemons: {
    backdoor: "daemons/backdoor.js",
    batchOrchestrator: "daemons/batch-orchestrator.ts",
    crawler: "daemons/dnet-crawler.js",
    fillShare: "daemons/fill-share.js",
    financeDispatcher: "daemons/finance-dispatcher.js",
    perfMonitor: "daemons/perf-monitor.js",
  },
  lib: {
    evaluators: {
      gang: "lib/evaluators/gang.js",
      hacknet: "lib/evaluators/hacknet.js",
      home: "lib/evaluators/home.js",
      player: "lib/evaluators/player.js",
      programs: "lib/evaluators/programs.js",
      pserv: "lib/evaluators/pserv.js",
      sleeve: "lib/evaluators/sleeve.js",
      stock: "lib/evaluators/stock.js",
    },
    types: {
      batcher: "lib/types/batcher.js",
      common: "lib/types/common.js",
      factions: "lib/types/factions.js",
      finance: "lib/types/finance.js",
      gang: "lib/types/gang.js",
      logger: "lib/types/logger.js",
      network: "lib/types/network.js",
      sleeves: "lib/types/sleeves.js",
      strategy: "lib/types/strategy.js",
    },
    utils: {
      batchCalculator: "lib/utils/batch-calculator.js",
      deployment: "lib/utils/deployment.js",
      factionHelpers: "lib/utils/faction-helpers.js",
      internalPlanner: "lib/utils/internal-planner.js",
      progress: "lib/utils/progress.js",
      provision: "lib/utils/provision.js",
    },
    batcherHelpers: "lib/batcher-helpers.js",
    constants: "lib/constants.js",
    evaluatorRunner: "lib/evaluator-runner.js",
    financePorts: "lib/finance-port.js",
    format: "lib/format.js",
    gang: "lib/gang-utils.js",
    logger: "lib/logger-client.js",
    metrics: "lib/metrics.js",
    network: "lib/network.js",
    paths: "lib/paths.js",
    player: "lib/player.js",
    sleeve: "lib/sleeve-utils.js",
    state: "lib/state.js",
    utilities: "lib/utils.js",
    executor: "lib/worker-executor.js",
  },
  managers: {
    dnet: "managers/dnet-master.js",
    gang: "managers/gang-manager.js",
    hash: "managers/hash-manager.js",
    sleeve: "managers/sleeve-manager.js",
  },
  payloads: {
    grow: "payloads/grow.js",
    hack: "payloads/hack.js",
    share: "payloads/share.js",
    weaken: "payloads/weaken.js",
    work: "payloads/work.js",
  },
  solvers: {
    AccountsManager: "solvers/solveAccountsManager.js",
    Anagram: "solvers/solveAnagram.js",
    CloudBlare: "solvers/solveCloudBlare.js",
    DeepGreen: "solvers/solveDeepGreen.js",
    DeskMemo: "solvers/solveDeskMemo.js",
    FactoriOs: "solvers/solveFactoriOs.js",
    FreshInstall: "solvers/solveFreshInstall.js",
    Laika4: "solvers/solveLaika4.js",
    Manager: "solvers/solveManager.js",
    NIL: "solvers/solveNIL.js",
    OctantVoxel: "solvers/solveOctantVoxel.js",
    OpenWebAccessPoint: "solvers/solveOpenWebAccessPoint.js",
    PHP54: "solvers/solvePHP54.js",
    Pr0verFl0: "solvers/solvePr0verFl0.js",
    Roman: "solvers/solveRoman.js",
    ZeroLogon: "solvers/solveZeroLogon.js",
  },
  tasks: {
    analyzeAug: "tasks/analyze-augmentations.js",
    cctSolver: "tasks/cct-solver.js",
    corp: "tasks/corp.js",
    crime: "tasks/crime.js",
    loot: "tasks/dnet-loot.js",
    phish: "tasks/dnet-phish.js",
    dnetSolver: "tasks/dnet-solver.js",
    faction: "tasks/faction-grind.js",
    train: "tasks/train.js",
    uni: "tasks/uni.js",
  },
  tools: {
    allocateDarkRam: "tools/allocate-darknet-ram.js",
    augScan: "tools/aug-scan.js",
    cctFinder: "tools/cct-finder.js",
    findDarknetPath: "tools/find-darknet-path.js",
    findPath: "tools/find-path.js",
    goOffline: "tools/go-offline.js",
    karma: "tools/karma.js",
    lootDarknetServer: "tools/loot-darknet-server.js",
    manDnetCrawler: "tools/manual-darknet-crawler.js",
    starter: "tools/starter.js",
  },
  ui: {
    batcher: "ui/batcher-ui.js",
    engine: "ui/engine-ui.js",
    finance: "ui/finance-ui.js",
    gang: "ui/gang-ui.js",
    infra: "ui/infra-ui.js",
    sleeve: "ui/sleeve-ui.js",
    helper: "ui/ui-helper.js",
  },
} as const;
